language: node_js
os: linux
node_js:
- lts/*
install:
- yarn install
script:
- yarn docs:build
deploy:
  provider: gh-pages
  local_dir: docs/.vuepress/dist
  token:
    secure: YoGsyPBElaLxPqf+ppNR66Uh5+UBZiEH8dGzNMr6ymBnhIsWr2XkPmmLGpS0OcG6aUxz/aG6ViuQRls7gEOdfWXf0GQru6i0iaCYtIBz5SR8Ri3KgCNDANEO2FB8PqPQ6W1AMSxuQs6MqZjWdJFuv/zFRgE8xh4ddkWxDrFPdaRvNBtNx016Q9e6Ea6PkqyX5PtvYnaHJymfB3HCTI3Hd+tacrhyF3zeQtHpsQqsVCVUnJpZ8DYtI61HtFr0RbNmiZH7PVfc/BIYaD6t0d0B8cU8Efmh9e8HLqbETELr+ovSB1JZgQTqPrJqYJQwr2DI9/v6DSGeKaZiYWOmE6TKJLDhVLJVWKhoCbfuA9bN4Bo1DV27YgaUOcAERVyXbtUUX+/o4bsXk2bPQ/fdBH+6Dzn3QO4VgiDRuyZ5j1dgr3hMGbZj8ysN7i3zobOvkwd1eGBKB2s4VbXbo4HUj/OpH2IFXW+GDPLH9THuneM08KnoUMi4Xd4ow9OEH/7tUbaq2eUXOVPkLcsTQ5r4AkCKA5PLcekENPC15gUs/ekTP91AYiCxpFkPUpnI0D7fda2eubVPWkF/6WqZWqzGwHBpiuGAc0rVLc9kATTrhl7ZyeUWdTs1YvLKSPePJig96414ypRITf3BkeFAPN1Ee8gvquNVqEuZOwV4R8SwfeZddSk=
  keep_history: true
  on:
    branch: master